name: CI

on: push

permissions: read-all
jobs:
  test-build:
    strategy:
      matrix:
        bun-version: [latest, "1.1.4"]
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout Repo
        uses: actions/checkout@v7

      - name: 🍞 Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: 🗃 Install Deps
        run: bun install --frozen-lockfile #--production

      - name: 📦 Build Package
        run: bun run bundle -o dist-ci --debug

      - name: ✅ Verify output with Commited
        #uses: hudsonm62/compare-action@v1
        run: diff -qr dist dist-ci
